package users.api.pojoclass;

public class ProjectPOJO {
// variable declaration.
	String projectName;
	String status;
	String createdBy;
	int teamSize;
//Note: use JSON file while decariong vas.(same name as in JSON file.)

//we should have to write an empty constructor.
	private ProjectPOJO() {}// Empty constructor is mandatory for De-Serialization.
	
//create constructor.
	public ProjectPOJO(String projectName, String status, String createdBy, int teamSize) {
		super(); //generated by-default.
		this.projectName = projectName;
		this.status = status;
		this.createdBy = createdBy;
		this.teamSize = teamSize;
	}
	
// create getters & setters.
	public String getProjectName() {
		return projectName;
	}
	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public int getTeamSize() {
		return teamSize;
	}
	public void setTeamSize(int teamSize) {
		this.teamSize = teamSize;
	}
	
	
}
